### ISSUE TITLE
Arrears Case Transfer

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#104]
This scrip will transfer the case to the arrears team on CAAS, send dord doc's to ncp/cp, and create caad note.

**Comment by RobertFewins-Kalb** [comment]
Is this a new script idea? Do you have something in the works?

From your description, I am concerned that this is very specific to your agency. In Anoka, each worker has an arrears-only caseload. I have been working on a case transfer script that could take the place of this. I am thinking of a possible enhancement to that script that will make a list of all arrears-only cases (found on CAST by reading the value of "Arrears Only") and transfer to the desired worker ID/position.

**Comment by RobertFewins-Kalb** [comment]
Enhancement Request...

Please indicate reasons why your agency transfers cases from one caseload to another...
* Arrears Only
* Locate

...

**Comment by gretchent74** [comment]
I do have this script completed.  I understand that not all counties have an arrears team and is very specific to my county.  This was my first script and I used it as a learning tool.  If anyone would like to the completed script let me know and I can share.
