### ISSUE TITLE
Fix issues on the NO PAYMENTS MONTH ONE-FOUR

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#119]
This was @GayS' script.

**Comment by RobertFewins-Kalb** [comment]
I'll take a crack at this'n

**Comment by RobertFewins-Kalb** [comment]
I'm submitting a fix. @GayS , please test to confirm that the functionality is what you originally intended?

**Comment by GayS** [comment]
Thanks for fixing – unfortunately I have no way to test – no access to PRISM.

**Comment by RobertFewins-Kalb** [comment]
Oh nos! It's in the master branch. I want to make sure it's OK before moving to beta.

Can you hand off to anyone in Stearns?

**Comment by GayS** [comment]
I’ll check w/Kelli ☺

**Comment by RobertFewins-Kalb** [comment]
I just checked with Kelli :) She's good to go.

**Comment by GayS** [comment]
Awesome!! Thanks! ☺

**Comment by RobertFewins-Kalb** [comment]
Closing this issue. It has been resolved.
