### ISSUE TITLE
Create "word docs file path" variable in globvar

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#12]
Because futureproofing

**Comment by theVKC** [comment]
@RobertFewins-Kalb: any chance you can do this while we train tomorrow?

**Comment by RobertFewins-Kalb** [comment]
There is a non-zero chance that can get done.

**Comment by RobertFewins-Kalb** [comment]
This has been updated for Anoka County. We can address this with other counties at April 2016 hackathon.

**Comment by theVKC** [comment]
@RobertFewins-Kalb and/or @levesswe: can I get an update on the progress of this issue, please? I just took a quick tear through GlobVar and saw nothing about this.

**Comment by RobertFewins-Kalb** [comment]
None progress

**Comment by theVKC** [comment]
OK. I'll be taking it.
