### ISSUE TITLE
Problem with NOTES - CLIENT CONTACT?

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#129]
Workers have reported some problems with NOTES - CLIENT CONTACT. Is it possible that It's calling old functions?

**Comment by RobertFewins-Kalb** [comment]
Old functions have been replaced. I have tested the CLIENT CONTACT script on case 0000002229-01 in the training region. Looks like all it working well. I will upload the fix.

**Comment by GayS** [comment]
Hey Robert - I'm still seeing the old functions in the CLIENT CONTACT did the pull request get merged?

**Comment by RobertFewins-Kalb** [comment]
Sounds like @GayS has an actual solution rather than my hypothetical one. Thanks, Gay!!

**Comment by levesswe** [comment]
Two more issues with the Client Contact CAAD script that should be quick fixes: the Client Contact script is entering the current date for the caad note instead of the client contact date.  Also, there is a stray comma after the client contact date in the caad note text.

**Comment by GayS** [comment]
The date of the client contact was moved into the CAAD note as the attempts to get the CAAD note date to enter correctly weren’t working.  We felt the majority of the contacts would be noted on the same day.  The comma separates the date and time.   Would you suggest that the time be a mandatory field?

**Comment by RobertFewins-Kalb** [comment]
Add a field for "CAAD Note Date?"

**Comment by levesswe** [comment]
I know that not everyone enters a time in the note, so I don't think the time should be required.  Perhaps the script could see if a time is entered and include the comma before the time if it is, or just put the date in if no time is entered.

I think for now, it is fine that the date is today's date, some of us were just surprised by the change.
