### ISSUE TITLE
NEW SCRIPT IDEA >> COPY CORD & DORD Docs from PRISM into Word

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#136]
For e-File reasons, it might be necessary to paperlessly (I'm going to copyright that word) pull documents out of PRISM, generate Word docs, and save them with the electronic case file.

**Comment by ChrisKast** [comment]
this would be awesome......................

**Comment by RobertFewins-Kalb** [comment]
There are issues with the formatting but it is nigh on ready.

**Comment by levesswe** [comment]
@RobertFewins-Kalb has been working on this... we have made huge progress, but still have a few details to work out.

**Comment by RobertFewins-Kalb** [comment]
I'm going close this. We were able to work on something, but the DORD and CORD docs are formatted strangely so it's inconsistent.
