### ISSUE TITLE
Bulk Transfer Cases - entire case load

### ISSUE THREAD

**Issue by GayS** [MN-CS-Script-Team/PRISM-Scripts#148]
Any ideas on how to transfer an entire case load from one worker to another worker #?  This could be useful in the case of new hires, case banking, etc.

**Comment by RobertFewins-Kalb** [comment]
Enter the same worker number in the first dialog for as many times as you need.

Anoka supervisors have asked for the ability to transfer an entire caseload and with this request I think an enhancement is in order.

**Comment by RobertFewins-Kalb** [comment]
But...a critical bug needs to be fixed...pull request to come on Monday. Sorry if you've tried to use the script and it doesn't work.

**Comment by GayS** [comment]
Great -  we seemed to be able to get some cases transferred after a couple of tries (user error - wrong worker #).  We were hoping to have the ability to enter current worker number, check here to transfer all cases, new worker number type of script.  Is that the direction you are going for Anoka?

**Comment by RobertFewins-Kalb** [comment]
@GayS , I'm going to submit a pull request for this...
