### ISSUE TITLE
Enhancement request for PALC Calculator

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#163]
Currently the script is set to go through the entire PALC screen and perform its own logic to determine whether the amounts are in the date range entered by the user.  There's really no reason to have the script do that logic when you can input the date range and filter results on the PALC screen.  Modifying the script in this way will save processing time, no need to scroll through unneeded pages of data.

**Comment by RobertFewins-Kalb** [comment]
Thanks, Wendy!
