### ISSUE TITLE
Needed: script instructions

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#17]
I know @Anoka-Script-Team has been making them using OneNote for a bit, but I'm not sure if all of the Child Support scripts have them. Regardless, we need to find a way to disperse the instructions for how to use PRISM scripts to other counties. Easiest option would be through a Word document, but I'll caution that it can get too big if we aren't careful (perhaps multiple documents, or a document for each script?). MAXIS scripts has a 60 page PDF I'm still trying to get all converted.

In any case, @paschell, do you think it'd be possible to either provide me your instructions (which I presume are available to all Anoka CSOs), or to draft up instructions and screenshots for each script made so far (excluding nav scripts)? This isn't a super big rush, but it'd be good to get instructions prepared on the front end instead of on the back end (again, speaking from experience here).

**Comment by paschell** [comment]
I don’t know that we have any instructions.  We deployed most scripts with quick how-to instructions through email.

I’ll see what I have saved and work on putting something together.  ☺

**Comment by ajluebbe** [comment]
Veronica, can we get an example of the detail of some MAXIS script instructions?

Alison

**Comment by paschell** [comment]
Alison,

There is some stuff on OneNote.  Look under Tech Tips and then Bluezone Scripts.  ☺

**Comment by theVKC** [comment]
I’ll send it via email. It’s stored on SIR.


Caution: This e-mail and attached documents, if any, may contain information that is protected by state or federal law. E-mail containing private or protected information should not be sent over a public (nonsecure) Internet unless it is encrypted pursuant to DHS standards. This e-mail should be forwarded only on a strictly need-to-know basis. If you are not the intended recipient, please: (1) notify the sender immediately, (2) do not forward the message, (3) do not print the message and (4) erase the message from your system.

**Comment by levesswe** [comment]
We are storing instructions on a provisional DHS-SIR page:

 https://www.dhssir.cty.dhs.state.mn.us/MAXIS/blzn/PRISMscripts/default.aspx

You will need to request access from Veronica Cary to be able to access them.
