### ISSUE TITLE
NEW SCRIPT IDEA >> Bulk script for identifying percent of arrears-only cases that have made a payment this fiscal year

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#172]
Anoka has a version currently being run. The problem is that it is very Anoka-specific. Having met with Jannell in Stearns County, I think I have found a way of broadening the script to make it work better for the collaborative.

**Comment by levesswe** [comment]
Assigning to @RobertFewins-Kalb!

**Comment by RobertFewins-Kalb** [comment]
Sweeeeeeeeeet!

**Comment by levesswe** [comment]
@RobertFewins-Kalb, this is working, right?  Can we close this issue?

**Comment by RobertFewins-Kalb** [comment]
I haven't taken this on....wowza. I probably should.

**Comment by RobertFewins-Kalb** [comment]
Progress has been made on a non-pay look up script. Currently in testing.

**Comment by RobertFewins-Kalb** [comment]
But it is now able to identify arrears-only cases.

**Comment by RobertFewins-Kalb** [comment]
Going to submit a pull request tomorrow with this. Knocking out the issues...
