### ISSUE TITLE
NEW SCRIPT IDEA >> USWT SCRUBBERS

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#174]
@levesswe , @paschell  and I were looking over the USWT scrubber script @kellijo81 submitted today. We had a thought about how to handle these scripts. Our thought is for a USWT Scrubber Main Menu script...

![image](https://cloud.githubusercontent.com/assets/7842016/8994264/e741fb02-36cf-11e5-9160-d006b55cdc66.png)

This would act only as a main menu and could run a script directly from it depending on the user selection.

**Comment by RobertFewins-Kalb** [comment]
@GayS , think of this as a DAIL scrubber but with a user selection menu.

**Comment by GayS** [comment]
I'm thinking @RobertFewins-Kalb  meant to leave this comment for @levesswe , @paschell

**Comment by RobertFewins-Kalb** [comment]
No, I was just tagging you. :)

I'm just thinking that USWT scrubbers could start to function like the DAIL scrubber in that there could be a USWT Scrubber main menu that runs the individual scrubber scripts.

**Comment by GayS** [comment]
Sorry – I’m sooo confused.  Non-FW speak – what is a USWT?

**Comment by theVKC** [comment]
This appears to have been opened for over a year. @MN-CS-Script-Team/scriptwriters, anyone feel up to taking this on, or giving me a status update on it? If nobody is interested in doing it by Monday's hackathon, I'd like to close it.

**Comment by levesswe** [comment]
The feedback that I received from users is that it would be nice to be able to select multiple bulk scripts to run, and this proposed dropdown would only select one at a time.  At some point in the future, it might be nice to do something with our bulk script menu - for now, I think it's okay to close this one.

**Comment by theVKC** [comment]
Per hackathon, closing this and marking as a sleeper.
