### ISSUE TITLE
Bulk_Failure_POF

### ISSUE THREAD

**Issue by kellijo81** [MN-CS-Script-Team/PRISM-Scripts#177]
We are getting an error on this line:
 
IF current_month = DatePart ("m", PAPL_most_recent_pay_date) THEN
 
It’s saying “mismatch”

**Comment by RobertFewins-Kalb** [comment]
Yes. Your variable names are not consistent. You never create the variable "current_month." In the previous line, you establish that current_month_minus1 = DatePart("M", DateAdd("M", -1, date)).

After the collaborative phone call, @levesswe , @paschell  and I looked the script over and made some updates. I will submit a fix this morning.

**Comment by kellijo81** [comment]
Okay that worked. Now, we're getting error on the EMReadScreen line:
	Call navigate_to_PRISM_screen ("CAWT")
		transmit
		EMReadScreen CAWT_type, 8, 5

**Comment by RobertFewins-Kalb** [comment]
Any takers? Collaborative powers, activate!!!

**Comment by kellijo81** [comment]
Okay that worked. Now we are at the end and are having difficulty getting it to purge.
Call navigate_to_PRISM_screen ("CAWT")
		transmit
		EMReadScreen CAWT_type, 5, CAWT_row, 45	  
			IF CAWT_type = "E0014" then
			EMWriteScreen "p", 4	
			transmit
			transmit
			PF3
			PF3
			End If

**Comment by RobertFewins-Kalb** [comment]
Yes!!! Nice work!
