### ISSUE TITLE
Script Question

### ISSUE THREAD

**Issue by kellijo81** [MN-CS-Script-Team/PRISM-Scripts#183]
I am trying to get my script to find a “blank” within one column, but it could be found in any row 9 through 18. How do you write that in script? Do you do row 9 through 18 like the highlighted part below or how does the script know it can be in any row within that one column?  Thanks!

EMReadScreen Revw_type, 1, 9-18, 75

**Comment by levesswe** [comment]
It’s not quite like what you have below.  Essentially, we will need to give it a command to check each column in row 9 through 18 individually, and then compare the value to blank.  We do that by creating a loop with a conditional statement inside.  Here’s an example of a simple loop you can copy and paste into your code, if I did it right ☺  :

For i = 9 to 18  ‘i is called a counter variable.  It’s function is to increment from 9 to 18 in this example.
          EMReadScreen Revw_type, 1, i, 75    ‘This tells the script to read a character at whatever i is, in the 75th column, and ‘assigns the value of Revw_type.
                    If Revw_type = “ ” Then
                              ‘Your conditional actions here
                    End If
          i = i + 1   ‘increases the counter variable by one.
Next ‘Tells the script to move to the top of the loop and repeat.  Loop ends when i = 19.

**Comment by kellijo81** [comment]
Thank you!! I was not aware of "i" and/or counter variables. . . still learning. lol

**Comment by levesswe** [comment]
Were you able to figure it out?  Can we close this issue?

**Comment by kellijo81** [comment]
Yes,  you can close it.

**Comment by levesswe** [comment]
Closing issue
