### ISSUE TITLE
STATS database path may or may not be working as intended

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#19]
I just need to run it through it's paces. I think it might be missing a set of quotes in there. We shall see.

1. Test it with different paths.
2. Test it with UNC and drive-letter paths.

**Comment by levesswe** [comment]
@RobertFewins-Kalb, this is working now, right?  Can we close this issue?

**Comment by RobertFewins-Kalb** [comment]
If it's a problem, it's not a problem for Anoka County.

Stearns folks -- @kellijo81 @GayS -- are you able to gather stats?
Wright folks -- @khiestand -- are you able to gather stats?
Dakota folks -- @gretchent74 -- are you able to gather stats?
Olmsted folks -- @margmac17 @ChrisKast -- are you able to gather stats?

(Sorry if I missed anyone)

**Comment by GayS** [comment]
The stat path is stored locally in the Global Variable file on line 12.

**Comment by theVKC** [comment]
I seem to remember the function may have been hardcoded with the Q:\ on it. @RobertFewins-Kalb or @levesswe, did you get rid of that function when we merged many CS functions with MAXIS FuncLib?

**Comment by RobertFewins-Kalb** [comment]
I think we're good... (from the GH GlobVar...)

![image](https://cloud.githubusercontent.com/assets/7842016/11793710/be584fa2-a272-11e5-9c65-db175e386d4d.png)

**Comment by theVKC** [comment]
I think @GayS confirmed yesterday that this is good to close.

**Comment by GayS** [comment]
Yes

**Comment by theVKC** [comment]
I'm hesitant to close it since I don't work with CS officially anymore. @levesswe, care to do the honors?

**Comment by levesswe** [comment]
Sure, closing this issue.
