### ISSUE TITLE
notice of continued service script on power pad under notes

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#195]
when i use this script the worklist is not not purging automatically.  The p is there but i have to push enter for each worklsit to be purged instead of it automatically being purged.  Also my intitials for the caad notet are not actually being added in the caad note.  Thank you.

**Comment by levesswe** [comment]
Gretchen, I wanted to add that I wasn't able to replicate the issue with your initials.  The script does not enter a CAAD note unless you put in some additional text to CAAD, and then it does.  This is something that we will clarify in the user documentation.
