### ISSUE TITLE
CSFuncLib: make the "run_from_GitHub" function replace Option Explicit if found

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#20]
This would allow our scriptwriters to write scripts that use Option Explicit, but would allow our redirect files to ignore it if found (because the redirect files would have already declared option explicit in my perfect world).

@RobertFewins-Kalb, I'm guessing you'll be interested in this concept.

**Comment by levesswe** [comment]
Closing this issue because MAXIS scriptwriters are going to address this issue.
