### ISSUE TITLE
Enhancement Request -- client contact

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#225]
Please verify that dates are being written MM/DD. It has been reported that it is writing M/DD for January 2016.

**Comment by khiestand** [comment]
@ RobertFewins-Kalb, I think this is working, I have not had an issue at all in 2016.

**Comment by theVKC** [comment]
FYI: two hackathons ago in MAXIS, we came up with a new method for this:

`footer_month = right("0" & datepart("m", date), 2)`

This takes up a single line and requires no logic whatsoever. It works quite well for any instance in which leading zeroes are required (PMIs in MMIS, anyone?).

**Comment by levesswe** [comment]
That is a thing of beauty.  Thanks, @theVKC   Closing issue, as this issue is resolved.
