### ISSUE TITLE
Enhancement >> NOTES - Adjustment needs err_msg handling

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#237]
NOTES >> Adjustment could use some better data validation. Looks like a great opportunity for some err_msg handling. At present the following variables are mandatory: worker_signature, reason_list, some checkboxes, but it looks like "reason_list" could use validation to be made mandatory.

Any takers?

**Comment by gretchent74** [comment]
I am working on this.  I will try to get done by early next week.

**Comment by RobertFewins-Kalb** [comment]
Thanks, @gretchent74!!

**Comment by levesswe** [comment]
This issue should be resolved.  Closing issue.
