### ISSUE TITLE
INSTRUCTIONS NEEDED

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#240]
I am reviewing our provisional SIR page. There are still a large number of scripts that need instructions. I am creating tasks in SIR for this work to get done. It sounds like @paschell and @levesswe have some instructions already made. They are going to get those uploaded ASAP.

When you can, please go to the provisional SIR page, under Tasks to see what you can do to get some instructions made. 

Currently, there are some scripts that are available to everyone that do not have instructions. Going forward, no scripts are going to be made available to all staff until those instructions are made.

Thank you, everybody!

**Comment by gretchent74** [comment]
I don't have access to the SIR page yet  but if someone will let me know what scripts need instruction, I am willing to write instructions for any script.  Thanks!

**Comment by paschell** [comment]
Hi Gretchen,  Some of the scripts with no instructions are:  Estab NPA DORD docs, Estab PA DORD docs, Court Order Requested, CSENet Info, No Pay months 1-4, ROP Detail, SOP Invoice, Waiver of Personal Services,  MES Financial DOCS, Intake Docs received.

Let me know which ones you may be interested in tackling and I will update the TASKS menu.  You can also send me the instruction document and I can upload to the SIR page.  Hopefully you will get access soon!!

**Comment by gretchent74** [comment]
Pam,
I completed CSENET info and Court Order Requested instructions.  I emailed them both to you as an attached word document.  I will let me know if I have time for anymore next week.

**Comment by RobertFewins-Kalb** [comment]
Closing this. I think the word is out there. Check the task list on the provisional SIR page to see what instructions need to be built.

Great work, all!!
