### ISSUE TITLE
CALI to Excel

### ISSUE THREAD

**Issue by khiestand** [MN-CS-Script-Team/PRISM-Scripts#253]
Could we add some text to the dialog to indicate if they do not check the box, what the script will do, or if not on the dialog, then in the instructions?  I don't see any instructions yet on the PRISM sir site.

**Comment by levesswe** [comment]
I just posted instructions to DHS-Sir.

**Comment by khiestand** [comment]
Karen P is wondering if the following adjustment can be made:
She would like to see a check box for the worker to check if they want the payment info included.
Right now does it automatically include the past payment info?  She would like that to be optional.

**Comment by RobertFewins-Kalb** [comment]
@khiestand, feel free to make that enhancement and add it to the version in master

**Comment by levesswe** [comment]
Resolves #271
