### ISSUE TITLE
FuncLib block: my name and user data should be removed, I think...

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#254]
Right now, it says "Veronica" a lot, and links to my account ("theVKC"). Right now it auto-redirects, but if I changed my account name, who knows?

Probably good to update it to reflect the current status and path. Just thought I'd let you know. I won't be able to work on this at present, obviously, but perhaps one of the talented PRISM scriptwriters can clean it up?

**Comment by levesswe** [comment]
@RobertFewins-Kalb , could you take care of this?

**Comment by RobertFewins-Kalb** [comment]
On it!

**Comment by RobertFewins-Kalb** [comment]
That's master done

**Comment by RobertFewins-Kalb** [comment]
I'm going to go ahead and close this. As changes are made to scripts in master, the funclib block change will trickle into beta and release.
