### ISSUE TITLE
BULK - FI Match Not Eligible for Levy

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#257]
We would like to revise to add functionality to prompt for purge if there is no current address on NCDD.

**Comment by theVKC** [comment]
This has been opened for a long time. @levesswe, do you have any news about it?

If nobody takes it by Monday's hackathon, I might close the issue. We can re-evaluate it at a later date if it's a priority.

**Comment by levesswe** [comment]
We may want to talk about this script idea in more detail, but unfortunately, I won't be at the Hackathon.  We have an existing BULK script - BULK - L5000 WORKLIST SCRUBBER.vbs in master that simply removes these worklists.  However, during testing we received feedback that it would be more helpful and more compliant with policy to modify this from being a "scrubber" to something that offers more to users.  Specifically, we are thinking to display NCP's current address from NCDD in the dialog, as well as the address associated with the bank account, and then prompt the user for possible actions: an update to the address, send out a postal verification to the bank account address, purge of the L5000 worklist, and/or add a free worklist for follow up.  If we do not follow up on this modification, someone (you) should investigate whether there are policy concerns for using the BULK - L5000 WORKLIST SCRUBBER.vbs as it is, or if it needs to be retired.  At this time, I do not have supervisor permission to work on this script idea.

**Comment by theVKC** [comment]
Per hackathon, we should close this issue and instead evaluate #405.
