### ISSUE TITLE
BULK - Review Case Referred

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#258]
Enhancement request to have the script check to see if there is an existing worklist on the case, and if not, prompt for purge.

**Comment by theVKC** [comment]
Any takers on this one? Is this a priority? @MN-CS-Script-Team/scriptwriters?

If nobody wants it by hackathon, I will close the issue.

**Comment by levesswe** [comment]
There is an existing script BULK - M8001 WORKLIST SCRUBBER.vbs in master that simply removes M8001 worklists, without regard for the date of them.  We received some feedback in testing that users were concerned that if there were otherwise no other worklists on the case, the script would delete the only worklist a newly assigned case might have.   

This script was intended for situations where an entire caseload is re-assigned (such as when a worker switches units).  There were concerns that if the script was used in other situations other than that for which it was intended, the script could remove M8001 worklists from a different date that the user might not expect to have removed.

My supervisors felt that the occasion to use this script was too rare to justify me putting time into it.  If we don't modify this script, we should look at whether BULK - M8001 WORKLIST SCRUBBER should be retired.

**Comment by theVKC** [comment]
Anyone have a strong objection to retiring BULK - M8001 WORKLIST SCRUBBER? @MN-CS-Script-Team/scriptwriters?

**Comment by theVKC** [comment]
Per hackathon, we should enhance it to look at the dates. However, this is not used frequently and as such is not a priority to do. We have decided to make this issue a sleeper issue, and retire the script for the time being. We can re-evaluate it at a later date. See  #406.
