### ISSUE TITLE
AMPP Review Notes Script

### ISSUE THREAD

**Issue by khiestand** [MN-CS-Script-Team/PRISM-Scripts#267]
I am writing an AMPP review notes script for the child support worker to use.  It will involve the three CAAD codes: E9851, E9852, E9853.

**Comment by levesswe** [comment]
Kelly, did you already see the Arrears Management script under NOTES?  It uses the same CAAD codes.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by khiestand** [comment]
Yes just saw that, oops!  Never mind!

**Comment by levesswe** [comment]
Closing this issue.
