### ISSUE TITLE
Evaluate NCOS bug?

### ISSUE THREAD

**Issue by khiestand** [MN-CS-Script-Team/PRISM-Scripts#270]
When we have a worker run this script, it is getting hung up with the date.  She tried it today and it stalls wanting to put the date as 4/1/2016 instead of 04/01/2016.  Is Prism friendly date in this script?  Maybe we can take a peek on Monday!

**Comment by levesswe** [comment]
Yes, let's check on that Monday. Hopefully it's a quick fix.
