### ISSUE TITLE
Review Pay Plan - DL is Suspended and Recent Payment Activity

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#280]
getting error for both scripts:  Script Error at Line 1, Column I: Name redefined.  Thank you.

**Comment by RobertFewins-Kalb** [comment]
@gretchent74, to what scripts are you referring specifically? Notes? Actions?

**Comment by gretchent74** [comment]
Both BULK SCRIPTS
review pay plan dl is suspended and review pay plan recent payment activity.

**Comment by RobertFewins-Kalb** [comment]
Should be working.

**Comment by RobertFewins-Kalb** [comment]
...now

**Comment by RobertFewins-Kalb** [comment]
Please let me know if the scripts are working. We can probably close the issue.

**Comment by gretchent74** [comment]
yes works great!

**Comment by RobertFewins-Kalb** [comment]
Yes!
