### ISSUE TITLE
BULK Review Pay Plan Recent Payment Activity

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#281]
error with date format 03/31/20166  instead of 03/31/2016 so script is getting stuck.

**Comment by RobertFewins-Kalb** [comment]
I think I was aware of this problem previously. What screen is the script getting stuck on?

**Comment by gretchent74** [comment]
palc

**Comment by RobertFewins-Kalb** [comment]
We need to be sure that we are writing the dates as MM/DD/YYYY on PALC

**Comment by RobertFewins-Kalb** [comment]
The script needs _create_mainframe_friendly_date_ instead of a simple _EMWriteScreen_
