### ISSUE TITLE
Global Variables Enhancement >> Add county code

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#283]
Thinking about report scripts, it might be easier if we can have the script autofill from the global variables file.

**Comment by RobertFewins-Kalb** [comment]
BULK - NO PAY REPORT needs this value to run. I will update the default Global Variables file in GitHub.

**Comment by RobertFewins-Kalb** [comment]
If you do not have a value for "county_cali_code" in your Global Variables, then BULK - NO PAY REPORT will not work for your agency.

**Comment by levesswe** [comment]
@RobertFewins-Kalb, we updated the global variables file, but it lists county_cali_code twice... Once the duplicate is removed, can this issue be closed?
