### ISSUE TITLE
Enhancement -- Rename "Sharing is Caring" Folder

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#291]
@wrightcountykaren suggested renaming the folder for professionalism.

**Comment by khiestand** [comment]
@RobertFewins-Kalb 
I don't think I have access to change the name of this folder??

**Comment by RobertFewins-Kalb** [comment]
You need to change the name of the files in the folder

**Comment by khiestand** [comment]
@RobertFewins-Kalb 
Ok I think I did it right, VC showed me

**Comment by RobertFewins-Kalb** [comment]
Splendid!
