### ISSUE TITLE
Anoka Specific Global Variables on BULK - NO PAY REPORT

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#309]
I see this code and this is specific to Anoka drive scrips and does not run on other counties cases.  Other scipts that I have reviewed that are live and worked do not have the same code as this script.
```
'LOADING GLOBAL VARIABLES--------------------------------------------------------------------
Set run_another_script_fso = CreateObject("Scripting.FileSystemObject")
Set fso_command = run_another_script_fso.OpenTextFile("Q:\Blue Zone Scripts\Child Support\Script Files\SETTINGS - GLOBAL VARIABLES.vbs")
text_from_the_other_script = fso_command.ReadAll
fso_command.Close
Execute text_from_the_other_script
```

**Comment by RobertFewins-Kalb** [comment]
Can you provide the link. That is a link to the Anoka County GlobVar, but that is not in NOTES >> PAY OR REPORT.

**Comment by RobertFewins-Kalb** [comment]
Also, the Global Variables call should not be on any scripts, they should be on the REDIRECT files.

**Comment by KallistaImdieke** [comment]
I'm sorry I guess it is the BULK - NO PAY REPORT that I tested. https://github.com/KallistaImdieke/PRISM-Scripts/blob/master/Script%20Files/BULK/BULK%20-%20NO%20PAY%20REPORT.vbs

**Comment by RobertFewins-Kalb** [comment]
Shnikeys!! That is entirely my fault. I will remove ASAP!! Thanks for reporting!!

**Comment by KallistaImdieke** [comment]
Thank you!

**Comment by KallistaImdieke** [comment]
Hey Robert,

I tried running that script and its saying that I am not logged into Prism but I am.  Any thoughts?

Kallista

**Comment by RobertFewins-Kalb** [comment]
What is the exact error message?

**Comment by KallistaImdieke** [comment]
I logged out of Prism and logged back in and now I am getting the message “your agency is not properly configured for this script. Please refer this error message to your scripts administrator.”

**Comment by RobertFewins-Kalb** [comment]
Any chance you could add a screenshot of just the error message?

**Comment by RobertFewins-Kalb** [comment]
Ah! Yes, you need to update your Global Variables. @levesswe recently made revisions that require updates on your end. You can easily remedy this by adding `county_cali_code = ` (and then your county's 3-digit code on CALI) to the Global Variables file. The template has it right under the `county_name` variable.

**Comment by KallistaImdieke** [comment]
[cid:image001.png@01D1AA0D.4361E180]

**Comment by RobertFewins-Kalb** [comment]
That did not work.

**Comment by RobertFewins-Kalb** [comment]
This is what your GlobVar should have

![image](https://cloud.githubusercontent.com/assets/7842016/15128318/be874b5c-1600-11e6-9caf-54efd7673494.png)

**Comment by RobertFewins-Kalb** [comment]
Except 

`county_name = "Stearns County"
county_cali_code = ` << whatever Stearns' code is (I'm not sure off the top of my head)

**Comment by KallistaImdieke** [comment]
Where is this located in the script??  Do you have the line number or is this located somewhere else?

**Comment by RobertFewins-Kalb** [comment]
It's your Global Variables file (I have no idea where Stearns keeps the cookie jar)

For Anoka County, it's lines 18 & 19
