### ISSUE TITLE
Create a global constant: blank = ""

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#31]
This is crazy that I didn't think of this earlier. I think it could make things easier for scriptwriters.

**Comment by theVKC** [comment]
I'm betting this is already in the MAXIS FuncLib if you're still using it. :)

**Comment by RobertFewins-Kalb** [comment]
Closing. This totally is in the MAXIS FuncLib and we totally are using it.
