### ISSUE TITLE
Is anyone having an issue with the Redirect Doc's Script

### ISSUE THREAD

**Issue by ChrisKast** [MN-CS-Script-Team/PRISM-Scripts#311]
I'm getting an error "Something has gone wrong..."

**Comment by RobertFewins-Kalb** [comment]
On it! URL error on the All Scripts doc. Thank you for reporting.

**Comment by RobertFewins-Kalb** [comment]
Should be working!

**Comment by ChrisKast** [comment]
Perfectly I might add.   Are you applying for the child support script writers job at the state?

**Comment by ChrisKast** [comment]
Somebody here asked if I was…………I laughed and said it would be like hiring Fred Flinestone to be a nuclear scientist………………..
