### ISSUE TITLE
Scripts Restructure Part Deux

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#313]
My restructure hit a snag. CASE TRANSFER (single case) is currently labelled as a notes and actions script (which I think is fine). The problem is that the main menu cannot find it. 

I am thinking this requires a second restructure eliminating the ACTIONS, NOTES, and BULK folders and just putting scripts in the single SCRIPT FILES folder.

For now, I am going to just make CASE TRANSFER an ACTIONS script. We can discuss this at collaborative phone call on 5/19

**Comment by theVKC** [comment]
I am not sure about this process, because I do not know the details. @RobertFewins-Kalb, can we talk about this at the meeting with Anoka next week please?

**Comment by RobertFewins-Kalb** [comment]
The thought was to eliminate the ACTIONS, NOTES, and BULK folders and have the scripts load based on the values stored in the all scripts file. The hope was that it would make it simpler for folks to submit pull requests and make the menus a little more flexible (in the future).

**Comment by theVKC** [comment]
Has any work progressed on this, @RobertFewins-Kalb?

**Comment by RobertFewins-Kalb** [comment]
nay

**Comment by theVKC** [comment]
OK, I'm going to close this for now and we can re-evaluate the idea later.
