### ISSUE TITLE
BULK- No Pay Report

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#321]
error: your agency is not properly configured for this script.  refer to scripts administrator.

**Comment by RobertFewins-Kalb** [comment]
You need to add `county_cali_code` variable to your Global Variables file...

![image](https://cloud.githubusercontent.com/assets/7842016/15439695/5d501720-1e97-11e6-937e-52c757a10349.png)

**Comment by gretchent74** [comment]
Perfect.  It works now.

**Comment by RobertFewins-Kalb** [comment]
https://github.com/MN-CS-Script-Team/PRISM-Scripts/issues/321#issuecomment-220699032
