### ISSUE TITLE
County Specific Changes problems

### ISSUE THREAD

**Issue by gretchent74** [MN-CS-Script-Team/PRISM-Scripts#327]
The 5 scripts that were requested to be removed for DAKOTA were only removed for the super users.  #324

**Comment by RobertFewins-Kalb** [comment]
Yes. Maintaining two lists allows agencies to test scripts before accepting them in production (particularly helpful for agencies that will join the collaborative in the future). You will need to remove Dakota from those scripts on this file...

https://github.com/MN-CS-Script-Team/PRISM-Scripts/blob/beta/ALL%20SCRIPTS.vbs

**Comment by gretchent74** [comment]
#328 fixed thanks you
