### ISSUE TITLE
Enhancement to BULK - CALI to EXCEL

### ISSUE THREAD

**Issue by paschell** [MN-CS-Script-Team/PRISM-Scripts#334]
Would like to add additional options to see if NCP has a known address and is there an open LETL to make the list more friendly for locating contempt eligible cases.

**Comment by theVKC** [comment]
Anyone interested in working on this one? @MN-CS-Script-Team/scriptwriters?

**Comment by theVKC** [comment]
Any takers from @MN-CS-Script-Team/prism-scriptwriters or @MN-CS-Script-Team/inactive-prism-scriptwriters? If nobody is interested by next hackathon (08/22) we will close it.
