### ISSUE TITLE
Functions update

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#349]
The functions for writing a variable to CAAD and entering a bullet item to CAAD should be updated using EMWriteScreen rather than EMSendkey.  EMWriteScreen is a more efficient way of writing the data and has fewer problems...

**Comment by theVKC** [comment]
Per last week's call, I'm taking this on.

**Comment by theVKC** [comment]
This issue has been moved to BZS-FuncLib: https://github.com/MN-Script-Team/BZS-FuncLib/issues/277

Closing here.
