### ISSUE TITLE
Enhancement to ACTIONS - F0104 DORD MEMO

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#362]
Create option to spell check the memo text.

The option will open a new Word doc and write the memo text to it, and then run the spell/grammar checker.  The user can skip or change as they wish to, and then the text (with any modifications) is sent back to the dialog for the user to preview or send to DORD F0104 Memo.

The only issue with this is that the Word document with the modified text will need to be closed by the user.

**Comment by levesswe** [comment]
We may be able to get it to close programmatically if we can figure out what method closes without saving changes.  “Close” isn’t it.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by levesswe** [comment]
Ohhh, I think I found a winning combination!

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
Good deal! What did you do?

**Comment by levesswe** [comment]
objDoc.Close(0)

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
Wonderful!!
