### ISSUE TITLE
REVW QW INFO - Bulk Script: description is wonky

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#369]
On this script the description that shows in prism when you click on the buttons is not correct it currently states "Purges all M8001 (REVW Case Referred) work list from your USWT"  But what it actually does is review all 2500 and 2501 work lists on your caseload and purges the work list if the employer is already on NCIP/CPID

Thank you!!

**Comment by theVKC** [comment]
On evaluation I'm not sure this is critical.

@levesswe, can I get an update?

**Comment by theVKC** [comment]
It should read: `"Reviews all L2500 and L2501 worklists on your caseload and purges the worklist if the employer is already on NCID/CPID."` I'll take care of it. :)
