### ISSUE TITLE
ENFORCEMENT INTAKE ACTION SCRIPT

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#370]
Issues with the word documents, when I select the Case Opening - Welcome Letter, Court Order Summary, or CP New Order Summary then I receive a error message. If I do not select those word documents then the script runs however when it get's to adding the CAWT work list the date is entering wrong 7/21/2016 it is missing the zero in front of the month, and it states that "the script could not navigate to the case note. There may have been a script error. Add case note manually, and report the error to a script writer."

Thanks!

**Comment by levesswe** [comment]
Because of the Word Documents, this should be an Anoka-only script.  The ACTIONS - GENERIC ENFORCEMENT INTAKE.vbs script is basically the same as this script without the Word documents, so that's the one you should test.  If you have Word documents your county uses that you would like to incorporate into the script, you can use this script as an example for how it could be done.

I think this script should be moved to Shared Code as Anoka is maintaining this script in our local menu structure.  Thoughts, @RobertFewins-Kalb ?

Thoughts, @RobertFewins-Kalb?

**Comment by jlmartinone** [comment]
I think Wright County would utilize this script. 
Thanks!

**Comment by KallistaImdieke** [comment]
I believe that Stearns County could benefit from this script.

**Comment by theVKC** [comment]
I would like to combine "generic enforcement intake" and "enforcement intake" into a single script. I will take this on. @levesswe , @RobertFewins-Kalb, or @paschell, please email me your Anoka-specific documents so I may extract Word bookmark requirements from them for integration statewide.

**Comment by levesswe** [comment]
Here are the Word files used in the Anoka-only enforcement intake script.  FYI, I believe the version available on Github is out of date from what we are currently using here in Anoka.  If you would like, I can do a pull request with the latest and greatest version...   Let me know.


[Enforcement Script Word docs.zip](https://github.com/MN-CS-Script-Team/PRISM-Scripts/files/407336/Enforcement.Script.Word.docs.zip)

**Comment by theVKC** [comment]
Yes, please get our scripts up-to-date. If you have any other scripts that you've updated without sharing with others, please get them updated as well. Thank you!

**Comment by theVKC** [comment]
@levesswe, can you please pull request your most recent version of this script in to us? Please and thank you!

**Comment by theVKC** [comment]
I believe #451 will resolve this issue, so I am closing this issue. :)

**Comment by levesswe** [comment]
Great, thanks!

**Comment by KallistaImdieke** [comment]
Hey @khiestand here is my dialog box Thanks!

'''VB.net
BeginDialog CS_intake_dialog, 0, 0, 371, 365, "CS intake dialog"
  CheckBox 15, 50, 145, 10, "Case Opening - Welcome Letter", NCP_welcome_ltr_check
  CheckBox 15, 80, 140, 10, "Court Order Summary", ncp_court_order_summary_check
  CheckBox 15, 90, 115, 10, "DORD F0021 Finacial Statement", NCP_Finacial_Statement
  CheckBox 15, 105, 150, 10, "DORD F0924 - Health Insurance Verification", NCP_health_ins_verif_check
  CheckBox 15, 120, 120, 10, "Notice of Arrears Reported", arrears_reported_check
  CheckBox 200, 95, 65, 10, "DORD F0100", dord_F0100_check
  CheckBox 200, 125, 65, 10, "DORD F0109", dord_F0109_check
  CheckBox 200, 150, 60, 10, "DORD F0107", dord_F0107_check
  CheckBox 190, 50, 130, 10, "Case Opening - Welcome Letter", CP_welcome_ltr_check
  CheckBox 190, 65, 120, 10, "DORD F0021 Finacial Statement", NCP_finacial_statement
  CheckBox 15, 65, 130, 10, "Child Care Verification", child_care_verif_check
  EditBox 15, 185, 140, 15, t_30_day_cawd_txt
  EditBox 15, 240, 140, 15, t_60_day_cawd_txt
  EditBox 240, 280, 110, 15, worker_name
  EditBox 240, 300, 110, 15, worker_phone
  EditBox 90, 335, 90, 15, worker_signature
  ButtonGroup ButtonPressed
    OkButton 255, 335, 50, 20
    CancelButton 310, 335, 50, 20
  Text 15, 340, 70, 10, "Sign your CAAD note:"
  Text 195, 85, 30, 10, "NPA"
  Text 195, 110, 95, 10, "MFIP, DWP, CCA"
  Text 195, 140, 35, 10, "MA only"
  Text 185, 305, 50, 10, "Worker phone:"
  Text 185, 290, 50, 10, "Worker name:"
  GroupBox 190, 180, 170, 35, "File Location on CAST"
  GroupBox 185, 35, 170, 135, "Letters to NCP"
  GroupBox 10, 35, 170, 100, "Letters to CP"
  Text 5, 0, 325, 10, "Motion to Set Case Initiation"
  GroupBox 5, 145, 175, 175, "CAWD notes to add"
  EditBox 15, 295, 120, 15, add_caad_txt
  Text 15, 280, 85, 10, "Worklist Text"
  EditBox 205, 195, 65, 15, Edit7
  Text 5, 15, 50, 10, "Case Number"
  EditBox 60, 10, 190, 15, Edit8
  Text 15, 160, 80, 10, "Calendar days until due"
  EditBox 95, 155, 70, 15, Edit9
  Text 15, 175, 55, 10, "Worklist Text"
  Text 15, 210, 80, 10, "Calendar days until due"
  EditBox 100, 205, 60, 15, Edit11
  Text 15, 225, 55, 10, "Worklist Text"
  Text 15, 265, 80, 10, "Calendar day until due"
  EditBox 95, 260, 60, 15, Edit12
EndDialog
'''

**Comment by KallistaImdieke** [comment]
whoops I sent this in the wrong one.  sorry.
