### ISSUE TITLE
NOTES - DATE OF THE HEARING EXPRO and JUDICIAL - move magistrates and attorneys to GlobVar

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#373]
It was brought to my attention today by a worker here in Stearns that this script does not include child support magistrates for Stearns County or the County Attorneys.  looks like this maybe a county specific script?  Is there a way to have this script pull in the Stearns County information (or all counties bases on a variable so it works for all counties?) as this script may start being used more by our county and others. Right now they just changed the name before adding the case note but as it maybe used more frequently it would be nice to have it pull in the correct information for all counties. . :-) 

thanks!  Kallista

**Comment by theVKC** [comment]
Any chance a county scriptwriter would want to take a look and identify possible updates needed for this one? @MN-CS-Script-Team/scriptwriters??

**Comment by theVKC** [comment]
OK, these should pull from global variables. @RobertFewins-Kalb and @levesswe, can you please ensure that your magistrates and attorneys are located in Anoka's global variables. If there are not already variables there, please let me know and we can standardize the variable. I'll take this on.

**Comment by theVKC** [comment]
See #248, need to ensure this is done and accurate.

**Comment by theVKC** [comment]
This was resolved with #479.
