### ISSUE TITLE
NOTES -PAY OR REPORT 

### ISSUE THREAD

**Issue by paschell** [MN-CS-Script-Team/PRISM-Scripts#374]
The first dialog box (Case information) 1.   does not pull in the case number, user has to enter, unlike all other scripts,  2.  in selecting the first report month/year is there a way to notify the worker that the month should start following the 1st paydate?  3.  The worklist should also contain the Attorney present at the hearing.  4.  The  CAAD note did not include the conditions, or county attorney who was in attendance.  The only thing on the CAAD note was the court file # and the county attorney #.

**Comment by theVKC** [comment]
From the description, it doesn't sound critical. Although, #382 resolves it, so I might incorporate this sooner-rather-than-later. Investigating a bit later after I clean up the rest of the GitHub assignments.
