### ISSUE TITLE
Modification to Fee Suppression Override

### ISSUE THREAD

**Issue by RobertFewins-Kalb** [MN-CS-Script-Team/PRISM-Scripts#375]
@wrightcountykaren has brought it to our attention that the Fee Suppression Override needs revision.

@gretchent74 has volunteered.

**Comment by gretchent74** [comment]
This script has been updated and a pull request made.  FYI.  I don't have supervisor access to suppress fees so little testing has been done.  Please let me know if you have any suggestions.  This script has been updated allow users to manual add date for fee suppression and to choose a standard caad note or create their own caad note.

**Comment by theVKC** [comment]
@gretchent74 is re-evaluating this script to fix her issue, as described above. Reopening the issue so I can track her progress, and we can continue to discuss it. Go @gretchent74! Good luck!

**Comment by theVKC** [comment]
Resolved in #438.
