### ISSUE TITLE
MOD CAAD NOTE: Name of script must change

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#387]
There's a non-critical error in this script because the filename cannot include a colon.

https://github.com/MN-CS-Script-Team/PRISM-Scripts/blob/master/Script%20Files/NOTES/NOTES%20-%20MOD%20CAAD%20NOTE:%20CONTACT%20CHECKLIST.vbs

That colon doesn't run on Windows, so it's non-editable in it's current state. I'll take the issue and resolve it, but I'm curious: can anyone use it?

**Comment by KallistaImdieke** [comment]
We have been using it here in Stearns with no issues.

**Comment by theVKC** [comment]
Thank you Kallista! It might just be a problem then for users using GitHub Desktop. Has anyone out there who uses GitHub Desktop experienced an issue while editing scripts?

**Comment by theVKC** [comment]
Also @RobertFewins-Kalb: I can see you moved the file, but I am not privy to the past info, so I'm not sure if you were the creator, so I'll say this to everyone...

Friendly reminder: any invalid Windows characters are invalid script-file-name characters.

**Comment by theVKC** [comment]
I'm elevating this work to critical, because I cannot do any processing of GitHub and it's now crashing my editor. I can't build documentation or demonstrate what-I'm-trying-to-do without having this resolved.

**Comment by KallistaImdieke** [comment]
I am trying to figure out how to do this right now i have to pull up the guide book i have I am not very good in github

**Comment by KallistaImdieke** [comment]
I think I may have submitted the change to you. If i did something wrong let me know Github is very new and confusing to me. Cant wait until you have a training on it like you said in the meeting!  thanks!
