### ISSUE TITLE
Global constant array

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#39]
For each Anoka Child support unit, we should maintain a list of worker information.  We should discuss the information that we need to track for each worker.  I am thinking name, title, phone number, etc.

**Comment by theVKC** [comment]
I've been playing with classes over in MAXIS. I'd be interested in collaborating on a unified worker class that works for both MAXIS and PRISM...

**Comment by levesswe** [comment]
Closing this issue for now.
