### ISSUE TITLE
Employment Verification needs work

### ISSUE THREAD

**Issue by jlmartinone** [MN-CS-Script-Team/PRISM-Scripts#394]
- [ ] No button - I do not know how to add a button - please help!
- [X] When it errors out in NCID/CPID it still exits and goes to CAAD
Other than the button I believe this is ready to be tested.

Thanks!

**Comment by theVKC** [comment]
Good luck!

**Comment by theVKC** [comment]
@jlmartinone, you did your part but I never did mine! Did you ever pull it in? Can you try a pull request?
