### ISSUE TITLE
NOTES - Waiver of Personal Service Button cut-off

### ISSUE THREAD

**Issue by khiestand** [MN-CS-Script-Team/PRISM-Scripts#395]
The button is cut off on the NOTES- Main menu for Waiver of personal service.

I might be able to do this, not sure.

**Comment by theVKC** [comment]
@khiestand, I'm betting you could. At the least, I could teach you how to do it, right?

I'm going to assign this to you. We should set up some time (remote or otherwise) to go over this process. Once I learn it, of course. :P

**Comment by theVKC** [comment]
We are retiring this script, so I am going to close the issue.
