### ISSUE TITLE
BULK - L5000 WORKLIST SCRUBBER - retire it

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#405]
Per hackathon 08/08, folks in the room indicated it may be wise to retire this script, because the policy could be considered "murky" (see #257). Looking for feedback from @MN-CS-Script-Team/prism-scriptwriters and @MN-CS-Script-Team/inactive-prism-scriptwriters alike. If nobody provides feedback by the end of this week, I may act unilaterally. :)

**Comment by paschell** [comment]
This script plays a very small part overall in worklist management.  A worker may receive 2 or 3 worklists per month regarding a non custodial parent's eligibility for levy.  Hardly worth the time.  Now if we could determine a list of worklists that have little bearing on a case and BULK them all together to purge monthly  that would be something!  A real true scrubber, versus lets have several scripts to purge  2 or 3 worklists.

**Comment by theVKC** [comment]
FYI: according to survey results, this script is unused.

**Comment by jlmartinone** [comment]
OMG…
I use it a TON – so does the other interstate worker!!!  Like at least a few times a day..

[cid:image001.png@01D1FC73.6060F2E0]Thank you,
Jodi Martin
Child Support Officer
Wright County
763.682.7439
Fax 763.682.8920

How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by theVKC** [comment]
You indicated that as a "no" on the spreadsheet according to my records, @jlmartinone...

**Comment by jlmartinone** [comment]
WHAT!!! That was an error for sure. I will re-look at the spreadsheet to be sure there are not any other errors.

[cid:image001.png@01D1FC75.98F8F240]Thank you,
Jodi Martin
Child Support Officer
Wright County
763.682.7439
Fax 763.682.8920

How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by paschell** [comment]
@jlmartinone   Are we are talking about the same script?  The L5000 FI MATCH RECD NCP NOT ELIG FOR LEVY?   

SirMilo info:  
"PRISM runs the FIDM batch process on the second Saturday of each month. The purpose of this program is to add eligible persons and to exclude persons no longer eligible for the data match. When a person is eligible, a record will be added to the Enforcement List (ENFL) screen with a remedy type of FIN (Financial Institution Data Match) with a status of ACT (Active). If the person is no longer eligible for data matching, the record's status will be updated to TER (Terminated). The person data will be reviewed each consecutive month thereafter to determine if they re-qualify for data matching at a later date."

Prism may determine the case no longer meets criteria for levy, but the record from the financial institution is still on FILD and FIAD.  

It's only run once a month.  I don't understand how you can use this several times daily as it is a scrubber meant to purge all the L5000 worklists that appear monthly.  Very few cases are affected monthly.  This script has little impact for a "bulk" script.

**Comment by jlmartinone** [comment]
SORRY!! I was thinking a different script.

[cid:image001.png@01D1FC76.A718DCE0]Thank you,
Jodi Martin
Child Support Officer
Wright County
763.682.7439
Fax 763.682.8920

How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by wrightcountykaren** [comment]
Here are my thoughts:

-          I’m wondering if the script is unused because it’s title is not very descriptive.  Maybe people don’t use it because it is not clear what it does?

-          Let’s find out what it does and why people aren’t using it.  Maybe it simply purges the worklist  L5000 FI MATCH RECD NCP NOT ELIG FOR LEVY?  If workers don’t want that worklist purged without reviewing something from it, let’s see if we can enhance the script to pull up a pop-up box to show the comparison data and then ask the question “purge worklist?”.

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by theVKC** [comment]
I tend to agree, @wrightcountykaren. We should try and enhance scripts where possible. I think (and this is on the agenda for Thursday) we should consider changing script names where they may be unclear.

**Comment by theVKC** [comment]
Per meeting today, this is a rare instance and a very, very low priority. It makes sense to enhance it to add worker intervention but is low on the list. We will retire it for now and can always revisit this one. Perhaps a bulk multi-worklist scrubber can incorporate this as well.

**Comment by theVKC** [comment]
Replaced with #456.
