### ISSUE TITLE
DATE OF HEARING EXPRO and JUDICIAL: can we merge these together?

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#408]
Seems silly to have two when one (and a dropdown) could do. Thoughts? @MN-CS-Script-Team/inactive-prism-scriptwriters @MN-CS-Script-Team/prism-scriptwriters 

If I do not hear by Friday 08/12, I shall act unilaterally.

**Comment by paschell** [comment]
Just a thought - the dropdowns may get too long if you combine district and ex pro for both the reason for hearing and also the judges and magistrates/referees.   Don't know if that should be a concern or not.

**Comment by theVKC** [comment]
I was thinking we could use different dialogs (or declare them dynamically). This way, it won't become too cumbersome.

**Comment by paschell** [comment]
That would work great!  I like the idea of only having 1 script for the one process.  Makes more sense.

**Comment by theVKC** [comment]
Per yesterday's meeting, we are merging them, adding GlobVar handling (it needs to check for judges/magistrates/attorneys), and calling the new script "Hearing Notes". And I'll be doing it. :)

**Comment by theVKC** [comment]
Confirmed: GlobVar handling is not correct for this script. The dialog contains hard-coded attorneys.

@paschell and @levesswe: you should ensure that Anoka's attorneys, magistrates, and judges are listed in Global Variables. When I pull the fix to this script, if you don't have your folks in your GlobVar, your workers will no longer have the dropdown. #BePrepared
