### ISSUE TITLE
select_cso_caseload - Add parameter for different code

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-CS-Script-Team/PRISM-Scripts#410]
'Loading the dialog to select the CSO
CALL select_cso_caseload(ButtonPressed, cso_id, cso_name)

![image](https://cloud.githubusercontent.com/assets/19214103/17491502/81cbe33a-5d6d-11e6-8928-7ec3844f56d4.png)
 
The dialog box refers to a specific script.  

Thanks!

**Comment by theVKC** [comment]
On it! Thank you!

**Comment by theVKC** [comment]
https://github.com/MN-Script-Team/BZS-FuncLib/issues/278 is the new version of this, because we've merged with FuncLib. Closing this issue.
