### ISSUE TITLE
Maintaining County 

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#43]
Can anyone help me figure out how to easily add multiple worker positions to the ComboBox?  Or do I need to do this by hand?

**Comment by RobertFewins-Kalb** [comment]
Here are two suggestions...

The easier way is to list them out by hand. If you want the user to select from a list of fruits, you would build the list like: "(select one)"+chr(9)+"Apple"+"Banana"+"Orange"+chr(9)+"Pineapple", fruit_choice

The more advanced way is to the create the list as a variable like so...
  list_of_fruits = "Apple"+chr(9)+"Banana"+chr(9)+"Orange"+chr(9)+"Pineapple"
And when you go to build the dialog... "(select one)"+chr(9)+list_of_fruits, fruit_choice
The nice thing about the "advanced way" is that you can store the list remotely in the global variables...like, for example, a list of county attorneys...and update the list once when it is being called in multiple scripts.


So it rather depends on how you are going to use the list...

**Comment by levesswe** [comment]
I believe this script is working as expected.
