### ISSUE TITLE
Evaluate shared-code vs new agency custom option, discuss at August 25 meeting

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#433]
This is the last part before we can merge with MN-Script-Team.

Essentially, now that you can drop script files into agency custom, how do folks feel about removing and depreciating scripts in the shared-code folder? Agencies using those scripts could simply copy them into their Agency Customized folder (once they reinstall scripts after the URL move, of course). 

Looking for feedback, will discuss at hackathon and the August 25 meeting.

**Comment by levesswe** [comment]
I am not sure that the shared code folder should be depreciated.  The shared code folder is intended to be a repository of county-specific scripts that may be good examples for script writers of other counties to work from if they want make their own agency specific version, or for scripts in development that are being worked on by multiple people in the collaborative to simplify collaborative efforts when not in the same room.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
As far as collaborating off site with others, that can be more easily accomplished with branching (and it preserves the integrity of the commit contributions).

As far as "agency specific" versions, I am moving toward integrating county-specific branching in other ways. We had great success allowing scriptwriters to implement county-specific logic in MAXIS scripts, and I believe that same process of integration (with if...then statements allowing customization) is the best bet considering the knowledge differences between scriptwriting vs. non-scriptwriting counties.

**Comment by levesswe** [comment]
I am not opposed to changing the way we have been doing things, but we will need clear, step-by-step instructions for users on how to collaborate off site with branching if you depreciate the folder.  I think the shared folder was nice especially for those less comfortable with Github.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
Per today's discussion, we will be replacing this folder/process with AGENCY CUSTOM and retiring it from the project.

**Comment by theVKC** [comment]
Today we shall integrate scripts within this folder with the project as a whole. :)

**Comment by theVKC** [comment]
#457 will resolve this issue, so I'm closing this one.
