### ISSUE TITLE
New Script Idea - Emancipation CAAD Note

### ISSUE THREAD

**Issue by jmarieraymond** [MN-CS-Script-Team/PRISM-Scripts#44]
Script to be used to update CAAD with date of anticipated graduation.  I think the script is done and I would like it to be tested.

**Comment by levesswe** [comment]
@jmarieraymond, I am assigning this issue to you!  How is your script coming along?  Can we close this issue?

**Comment by jmarieraymond** [comment]
Yes, I believe it is as good as it will get, you can close it.

Thanks!
Jessica
