### ISSUE TITLE
Remove "AGENCIES THAT USE" (whitelist) functionality from all main menu scripts

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#446]
This was a piece of feedback received during the meetings this month: folks would rather blacklist individual scripts locally (even per user or per user group) rather than the whitelist functionality currently deployed. In other words, get rid of the "AGENCIES THAT USE" functionality and make all scripts available to all counties.

I would like to tackle this one today so we can more easily evaluate scripts during tomorrow's meeting.

**Comment by levesswe** [comment]
@theVKC : question - what procedure we are to take to blacklist individual scripts from use by users of the agency, now that all scripts are available to all users?

**Comment by theVKC** [comment]
The blacklist functionality is not available yet. At this point, just inform folks of which scripts they should and should not use. The majority of agencies have at this point chosen to allow all scripts, so implementing the blacklist has not been a priority. It has its own FuncLib issue, tied to the main menu generation process as well.
