### ISSUE TITLE
DES Worklist

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#45]
Had issues stopping script when clicking Cancel in the loop containing Must Enter Employer.   (now this is fixed- this is just a test issue for training)

I have been working on his script issue but could use help.

**Comment by RobertFewins-Kalb** [comment]
I cannot find the script in question in GitHub. Additionally, there is another issue created that seems identical to this one. I will close this issue and redirect your discussion to issue #52
