### ISSUE TITLE
New Script Idea - Court Order Request

### ISSUE THREAD

**Issue by khiestand** [MN-CS-Script-Team/PRISM-Scripts#46]
This is a caad note script that will input details of the court order request: date order requested, county or person requested from, request method, court file number, order type, and worker signature.  After caad noting this info, script navigates to a worklist but does not save the worklist so the CSO can enter more info if they want before saving it.  I have been working on this idea and it is pretty much complete.

**Comment by levesswe** [comment]
@khiestand, are you still working on this script, or can this issue be closed?

**Comment by khiestand** [comment]
@levesswe This is done, it is on the power pad already :-)

**Comment by levesswe** [comment]
Closing issue
