### ISSUE TITLE
New Script Idea - MES docs sent

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-CS-Script-Team/PRISM-Scripts#47]
Creates CAAD note for 5 of the typical documents that are sent to a client for an MES action along with a requested return date.  It also makes a worklist "Have MES docs been returned" for 21 days later than today.
I have been working on this issue and I think the script is 100% complete, just waiting for review

**Comment by levesswe** [comment]
@wrightcountykaren, are you still working on this script, or can this issue be closed?

**Comment by levesswe** [comment]
Closing issue, currently being tested by beta team.
