### ISSUE TITLE
PA Case Review Script

### ISSUE THREAD

**Issue by margmac17** [MN-CS-Script-Team/PRISM-Scripts#48]
This script would be used when reviewing a new case referral from IVA. We do a CAAD note that outlines the facts of the case as it stands at this time. My script is probably about 50% finished at this time.

**Comment by levesswe** [comment]
Are you still working in on this script, Margaret?  Or can this issue be closed?

**Comment by margmac17** [comment]
I have not had any time to finish it yet but can I close it anyway?
margaret

**Comment by levesswe** [comment]
I'll close this issue for you, Margaret!  Thanks!
