### ISSUE TITLE
New Script Idea- Contempt Review 

### ISSUE THREAD

**Issue by KGhennepin** [MN-CS-Script-Team/PRISM-Scripts#50]
This script helps determine if the case would qualify for contempt and case note all information reviewed by worker. I am currently working on this issue & need to add more information.

**Comment by levesswe** [comment]
How is this script going? Are you still working on this script or should we close this issue?

**Comment by RobertFewins-Kalb** [comment]
After some discussion, this sounds like something would be better served as an agency-specific script. Closing.
