### ISSUE TITLE
New Script Idea - Case Review

### ISSUE THREAD

**Issue by ChrisKast** [MN-CS-Script-Team/PRISM-Scripts#51]
I'd like the script to gather pmt info from prism and determine if there is an existing contempt order.  I've been plugging away at this and have a script about 90% complete.  Need to have the script search SUOD for court order type CTM and then populate the dialog box and CAAD note.

**Comment by levesswe** [comment]
Assigning to you!  How is the script coming along?

**Comment by ChrisKast** [comment]
Well.....to be honest I haven't been able to spend any time on scripts.  In the last couple of months we've gone completely paperless and moved our offices from one building to another which has had a huge impact on how we operate.  I've also missed many of the Thursday meetings due to some mandatory trainings that are scheduled for Thursdays.  I'm hoping to get back at them fairly soon.

**Comment by paschell** [comment]
Robert and I worked on this script a very long time ago, and it pretty much bombed as it got too big.

With all the other scripts being designed, DL and Case Review No payment, I am wondering if it is worth resurrecting.

**Comment by levesswe** [comment]
@ChrisKast , do you want to continue to keep this issue open and plan to finish the script, or close this issue?

**Comment by ChrisKast** [comment]
You can close it.  It was just something I was messing with at the initial training.

Thank you.

**Comment by levesswe** [comment]
Closing this issue.
