### ISSUE TITLE
DES Worklist Script

### ISSUE THREAD

**Issue by mjblees** [MN-CS-Script-Team/PRISM-Scripts#52]
Have issues with script adding a 0 in CAAD Note.  Do not know how to get rid of the "0".  I have a script that Dawn Jacobson and I have been working on together at script training and unsure if this script is going to be useful.

**Comment by levesswe** [comment]
@mjblees  Is this still a problem?  Can this issue be closed?

**Comment by levesswe** [comment]
As we decided at the 3/24/2016 meeting, we are closing this issue for now.
