### ISSUE TITLE
New Script Idea - Document Generation 

### ISSUE THREAD

**Issue by levesswe** [MN-CS-Script-Team/PRISM-Scripts#54]
I want to be able to select from a list of documents to open in Microsoft Word.  I would like to have information from PRISM insert into the Word Documents using Form Fields or Bookmarks (Thinking this should be a custom function).  I would like the user to select whether they want to just open the Word Document in Word for further editing or, select to print the document directly, (by-passing opening the document for editing).  I would like the print function to print to both the default printer and to print to the virtual printer to print in Onbase.  

I know, I ask for a lot.  The good news is, I'm willing to help make it happen!

**Comment by RobertFewins-Kalb** [comment]
@levesswe  willing to take this one?
