### ISSUE TITLE
Emancipation Review

### ISSUE THREAD

**Issue by SFHennepin** [MN-CS-Script-Team/PRISM-Scripts#56]
script should delete case number, include court order (autofill from suol screen as may be other state court order), include age of majority as other states have different age of majority, include if more than one child is this a per child order? Change expected date of graduation to emancipation date. 
Have been working on this script in training but once completed thought of additional ideas.

**Comment by levesswe** [comment]
@SFHennepin , how is this script going?  Is this issue resolved?

**Comment by RobertFewins-Kalb** [comment]
@gretchent74 is working on an emancipation script. It also sounds like this would be better served as a  agency-specific script. Closing.
