### ISSUE TITLE
Notes Scripts----Client Contact---Issue with the date in dialog box & CAAD

### ISSUE THREAD

**Issue by ChrisKast** [MN-CS-Script-Team/PRISM-Scripts#58]
I've been trying to use the Client Contact scripts and it appears that the date in the dialog box doesn't auto populate the first "0"----3/17/2015 when it should be 03/17/2015.  You wouldn't thing that it's a big deal but since it pulls into CAAD it will error out when you hit enter because the date will not be in the correct format.  It appears on CAAD for me as 3/17/20155.  This could all be a user error because lord knows I'm pretty green at this but I just wanted to call it to someone's attention.  I peeked at the script but didn't see an obvious fix.

***If you fix the date in the dialog box it pulls to CAAD correctly so I think the issue is how it populates the dialog box itself.

**Comment by theVKC** [comment]
?Hey @RobertFewins-Kalb, are you thinking what I'm thinking? Custom function for entering dates on CAAD?



NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by RobertFewins-Kalb** [comment]
chin_stroke ... yes, @theVKC ... create_PRISM_friendly_date ...?

**Comment by theVKC** [comment]
Let’s do it.


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by levesswe** [comment]
See #81
