### ISSUE TITLE
New Script Idea - Payment Received Note

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#59]
CAAD Notes when payment recieved at office and is being sent to Payment Center. 

95% done - just finishing and then reviewing.

**Comment by Dmjacob** [comment]
@theVKC - I am having 3 issues with this script.  How would you like me to send it so you can take a look?  Pull Request?
   
Issue 1- I put in looping to msgbox if no signature was entered - and it won't let me click OK or the X to escape the msgbox and get back to enter the signature.   I can't locate anything in my notes from training on how to fix this. 

Issue 2- I am wondering if there is an easy way to leave out the line "on behalf of" from the CAAD note - if it is left blank when fililng in the dialog box.   

Issue 3- Is there an easy way to make the $ sign and .00 required or show up on this note or in your experience is it better to allow the user to enter it.   

Thank you!

**Comment by RobertFewins-Kalb** [comment]
Solution to Issue 2 - IF "on behalf of" (whatever the variable name is) <> "" (that's a back-to-back quotation mark) THEN CAAD note the information.

**Comment by RobertFewins-Kalb** [comment]
Solution to Issue 3 - FormatCurrency(variable)

FormatCurrency is a command that returns a $##.## for any numeric value.

**Comment by Dmjacob** [comment]
@RobertFewins-Kalb - i am not understanding the solution for Issue 2 - i would want it to omit the line all together and not CAAD note anything.    So far I have this as the line and don't know what to put after the THEN...

IF On_Behalf_Of <> "" THEN

**Comment by Dmjacob** [comment]
Where do i enter the FormatCurrency command in my script? 

(Thank you Robert?)

**Comment by RobertFewins-Kalb** [comment]
Check out w3school for a good tutorial on FormatCurrency (http://www.w3schools.com/vbscript/func_formatcurrency.asp)

**Comment by Dmjacob** [comment]
I was just doing a search on there.  Thank you!!

**Comment by levesswe** [comment]
@mjblees, do you know if this script is still being worked on?

**Comment by levesswe** [comment]
As we decided at the 3/24/2016 meeting, we are closing this issue for now.
