### ISSUE TITLE
New Script Idea - Service of Process 

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#60]
CAAD Notes when service of process is sent out.  

95% done - just finishing and then reviewing.

**Comment by Dmjacob** [comment]
@theVKC - After investigating I don't believe these are duplicates.  I think we just need to rename them.  They are for different tasks.  I will look further into renaming them next week.   Thank you!

**Comment by levesswe** [comment]
@mjblees, do you know if this script is still being worked on?

**Comment by levesswe** [comment]
As we decided at the 3/24/2016 meeting, we are closing this issue for now.
