### ISSUE TITLE
Fee Suppression

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-CS-Script-Team/PRISM-Scripts#73]
Idea to write a script to suppress the 2% state fee code when MNSure is open.  (Interface issue)

**Comment by theVKC** [comment]
Good luck!

**Comment by wrightcountykaren** [comment]
This is mostly done.  Thank you Robert for your help/suggestions!
It still has a problem.  The PRISM friendly date issue.  This script changes the fee eligible date out by 1 year, but it is not correctly adding the leading 0's on the date.  As soon as that has been fixed this script is ready to go :)

**Comment by wrightcountykaren** [comment]
The script is now working.  I just did a new pull request.

**Comment by levesswe** [comment]
Can this issue be closed, @wrightcountykaren?

**Comment by levesswe** [comment]
@wrightcountykaren indicated that this issue is resolved and can be closed.
