### ISSUE TITLE
New Script Idea - Case closure Criteria 

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#77]
Hope to work on this before the next meeting.

**Comment by levesswe** [comment]
@Dmjacob, how is this script coming along?

**Comment by Dmjacob** [comment]
@levesswe - sorry to take so long to respond.  I just got back from Maternity leave for 12 weeks.   I am trying to catch up on my work here and then plan to look over my progress prior to going out.   I do not believe I started this one though.
