### ISSUE TITLE
New Script Idea - DVS Access CAAD note

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#78]
Hope to work on this next week.   Please let me know if the L code happens.

**Comment by levesswe** [comment]
@Dmjacob, wondering how this script is coming along.

**Comment by levesswe** [comment]
@mjblees, do you know if this script is still being worked on?

**Comment by levesswe** [comment]
As we decided at the 3/24/2016 meeting, we are closing this issue for now.
