### ISSUE TITLE
New Script Idea - Transferring file out CAAD note

### ISSUE THREAD

**Issue by Dmjacob** [MN-CS-Script-Team/PRISM-Scripts#79]
Hope to work on this next week.

**Comment by levesswe** [comment]
@Dmjacob, are you still working on this one?

**Comment by levesswe** [comment]
@mjblees, do you know if this script is still being worked on?

**Comment by levesswe** [comment]
As we decided at the 3/24/2016 meeting, we are closing this issue for now.
