### ISSUE TITLE
NOTE - Client Contact

### ISSUE THREAD

**Issue by GayS** [MN-CS-Script-Team/PRISM-Scripts#81]
The caad note doesn’t F8 to allow text to go to the next screen and just continues to write over the first 6 lines of text.

**Comment by khiestand** [comment]
Also, I think this script could be re-named, as you can use it to contact financial workers, other state and county CSO's, the helpdesk etc.  Maybe just call it Contact Note or something to that effect?

**Comment by levesswe** [comment]
@khiestand, would you like to be assigned this issue about possible change to the name?  I think it would be okay to rename the text in the dialog and/or button, but I don't think it's worth it to rename the script.  Thoughts?

**Comment by khiestand** [comment]
@levesswe  I agree with you about renaming the text in the dialog and button.  Also, I am not sure the T1107 CONTACT WITH MN VITAL RECORDS contact type ever got saved?  I know you worked on that at 2/8/16 hackathon but when I am back at my desk at wright Co, the option is still not listed in the dropdown?  I just checked the code on Github and it is listed in the dropdown, so not sure what that could be?  Can you test it at Anoka and see if that option is listed in the dropdown??

**Comment by GayS** [comment]
It will get very confusing if the script is named one thing on the power pad and within the dialog box and another in the master branch and in stats.  I would recommend that the script name change to be consistent everywhere......my two cents.

**Comment by khiestand** [comment]
Agree, it wouldn't be that hard to re-name the script itself too would it??

**Comment by GayS** [comment]
I don't believe so.

**Comment by levesswe** [comment]
Try accessing it again for the contact with vital office, Kelly.  I think I saved it in the wrong branch.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by levesswe** [comment]
In discussing this issue at our meeting today, we discussed that the ramifications of changing the name is not worth the benefit.
