### ISSUE TITLE
Medical Support Review

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#89]
Template for medical insurance with worklists.
Suggestion:  When CPPD, CPKD, NCPD, NCKD is updated  a caad and cawt will be created.

**Comment by theVKC** [comment]
@ajluebbe, should we set a deadline on this? Is it a priority? Would you prefer to close it?

I know you're out this week: if I don't hear from you on the subject by next Friday 08/12, I am planning on closing the issue. :) #cleanup

**Comment by theVKC** [comment]
Per hackathon Monday 08/08, we should make this an actions script. If no-one takes this in the next month or so, we may close it, but @TammyStearns believes an upcoming project might help take care of some of this.

**Comment by theVKC** [comment]
I'm closing this issue due to lack of interest/discussion right now. We can always revisit it.
