### ISSUE TITLE
Locate 

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#94]
Script will be a template that worker will use to check off the locate tools they used during their locate check.  The checked boxes will carry over to a CAAD note.  A worklist will be created for the next locate action to take place per state direction
ASSIGNED TO ANOKA
LPE

**Comment by khiestand** [comment]
I can help with this one, we have a worker in Wright with the same idea!

**Comment by KathyMutchler** [comment]
Is anybody working on this one?  I'm at training and would like to work on it. @RobertFewins-Kalb @levesswe

**Comment by RobertFewins-Kalb** [comment]
@KathyMutchler & @khiestand ... stop, collaborate and listen!

**Comment by RobertFewins-Kalb** [comment]
This was completed today! Closing issue.
