### ISSUE TITLE
BULK Script for Notice of Continued Service Letter

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#95]
Jovan???

**Comment by RobertFewins-Kalb** [comment]
@levesswe and I teamed up to make BULK - EVALUATE NOCS.vbs

Going to submit a pull request

**Comment by RobertFewins-Kalb** [comment]
Resolved with #122 

Anoka County is going to be testing this script in July. Any other agencies interested in testing? (I will leave this issue open for continued discussion.)
