### ISSUE TITLE
Bulk Script - Review case not payment - E0002

### ISSUE THREAD

**Issue by ajluebbe** [MN-CS-Script-Team/PRISM-Scripts#96]
Jovan???

**Comment by RobertFewins-Kalb** [comment]
We have an outline... any takes?

**Comment by RobertFewins-Kalb** [comment]
We put together a beast of a script that provided a lot of information to the user, but we were hitting an exception access violation. It sounds like this is being broken into smaller parts. Sounds like @levesswe is allocating resources to this project.

**Comment by theVKC** [comment]
@levesswe, can I get an update on this? If it's not happening anytime soon, I'd like to close the issue and we can revisit it later.

**Comment by paschell** [comment]
Hey VKC - we can revisit this one.  We have been waiting on the State Office to create a NON-pay letter in DORD.  Maybe once that happens we can bring this one back.

**Comment by theVKC** [comment]
Good deal. Closing.
