### ISSUE TITLE
File path for stats database is not being set as variable, correct ASAP

### ISSUE THREAD

**Issue by theVKC** [MN-CS-Script-Team/PRISM-Scripts#99]

**Comment by levesswe** [comment]
@RobertFewins-Kalb, is this working now?  Can we close this issue?

**Comment by RobertFewins-Kalb** [comment]
If it's a problem, it's not a problem for Anoka County.

Stearns folks -- @kellijo81 @GayS  -- are you able to gather stats?
Wright folks -- @khiestand -- are you able to gather stats?
Dakota folks -- @gretchent74 -- are you able to gather stats?
Olmsted folks -- @margmac17 @ChrisKast -- are you able to gather stats?

(Sorry if I missed anyone)

**Comment by levesswe** [comment]
I believe this issue is resolved, closing issue.
